# Generated by Django 3.2.5 on 2021-09-01 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0002_auto_20210824_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
