# Generated by Django 3.2.5 on 2021-09-06 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlist', '0005_auto_20210905_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='liked_by',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='liked by'),
        ),
    ]
