# Generated by Django 3.2.5 on 2021-09-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wishlist', '0006_alter_useractivity_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contenttypes.contenttype'),
        ),
    ]
