# Generated by Django 3.2.5 on 2021-08-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='profile_pc',
            field=models.ImageField(blank=True, default='/images/shop_1.png', null=True, upload_to='profile_pics'),
        ),
    ]
