# Generated by Django 3.2.5 on 2021-08-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofilemodel_profile_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_pc',
            field=models.ImageField(blank=True, default='/images/no_picture.png', null=True, upload_to='profile_pics'),
        ),
    ]
