# Generated by Django 3.2.5 on 2021-08-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_pc',
            field=models.ImageField(blank=True, default='images/profile_pics/no_picture.png', null=True, upload_to='profile_pics'),
        ),
    ]
