# Generated by Django 3.2.5 on 2021-08-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofilemodel_profile_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='address2',
        ),
    ]
