# Generated by Django 3.2.5 on 2021-09-05 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20210824_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='postcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_pc',
            field=models.ImageField(blank=True, default='images/profile_pics/no_picture.png', null=True, upload_to='profile_pics', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
