# Generated by Django 3.2.5 on 2021-09-05 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0004_auto_20210905_0947'),
        ('shop', '0006_auto_20210905_0947'),
        ('watches', '0005_auto_20210905_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True, verbose_name='price')),
                ('first_name', models.CharField(max_length=30, verbose_name='name')),
                ('last_name', models.CharField(max_length=30, verbose_name='second name')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=30, verbose_name='country')),
                ('company', models.CharField(max_length=75, verbose_name='company')),
                ('address1', models.CharField(max_length=50, verbose_name='address')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('postcode', models.CharField(max_length=30, verbose_name='postcode')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('mobile', models.ManyToManyField(related_name='checkouts', to='mobile.MobilePhone', verbose_name='mobile phones')),
                ('products', models.ManyToManyField(related_name='checkouts', to='shop.Products', verbose_name='products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('watches', models.ManyToManyField(related_name='checkouts', to='watches.WatchModel', verbose_name='watches')),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkouts',
            },
        ),
    ]
