# Generated by Django 3.2.5 on 2021-07-28 10:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='phones')),
                ('price', models.FloatField()),
                ('real_price', models.FloatField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('post_views', models.IntegerField(blank=True, default=0, null=True)),
                ('long_description', ckeditor.fields.RichTextField()),
                ('additional_info', models.TextField()),
            ],
            options={
                'verbose_name': 'mobile phone',
                'verbose_name_plural': 'mobile phones',
            },
        ),
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'phone brand',
                'verbose_name_plural': 'phone brands',
            },
        ),
        migrations.CreateModel(
            name='PhoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'phone category',
                'verbose_name_plural': 'phone categories',
            },
        ),
        migrations.CreateModel(
            name='PhoneColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'phone color',
                'verbose_name_plural': 'phone colors',
            },
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mobile.mobilephone')),
            ],
            options={
                'verbose_name': 'mobile image',
                'verbose_name_plural': 'mobile    images',
            },
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mobile.phonebrand'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mobile.phonecategory'),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='color',
            field=models.ManyToManyField(related_name='mobile', to='mobile.PhoneColor'),
        ),
    ]
