# Generated by Django 3.2.5 on 2021-07-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonecolor',
            old_name='title',
            new_name='code',
        ),
    ]
