# Generated by Django 3.2.5 on 2021-08-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_rename_title_phonecolor_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneimage',
            options={'verbose_name': 'mobile image', 'verbose_name_plural': 'mobile images'},
        ),
    ]
