# Generated by Django 3.2.5 on 2021-09-05 04:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_phoneimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilephone',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='additional_info',
            field=models.TextField(verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mobile.phonebrand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mobile.phonecategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='color',
            field=models.ManyToManyField(related_name='mobile', to='mobile.PhoneColor', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='image',
            field=models.ImageField(upload_to='phones', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='long_description',
            field=ckeditor.fields.RichTextField(verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='post views'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real price'),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='title',
            field=models.CharField(max_length=122, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='phonecategory',
            name='title',
            field=models.CharField(max_length=122, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='phonecolor',
            name='code',
            field=models.CharField(max_length=122, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='phonecolor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='phoneimage',
            name='image',
            field=models.ImageField(upload_to='phone', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='phoneimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='mobile.mobilephone', verbose_name='product'),
        ),
    ]
