# Generated by Django 3.2.5 on 2021-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='video_image',
            field=models.FileField(default=False, upload_to='videos/%y'),
        ),
    ]
