# Generated by Django 3.2.5 on 2021-09-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(upload_to='teammates', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='job',
            field=models.CharField(max_length=120, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='name',
            field=models.CharField(max_length=125, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='additional_image',
            field=models.ImageField(upload_to='additional', verbose_name='additional image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='info',
            field=models.TextField(verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='price_info',
            field=models.FloatField(verbose_name='price info'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
