# Generated by Django 3.2.5 on 2021-08-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210819_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
