# Generated by Django 3.2.5 on 2021-07-28 10:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'watch brand',
                'verbose_name_plural': 'watch brands',
            },
        ),
        migrations.CreateModel(
            name='WatchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'watch category',
                'verbose_name_plural': 'watch categories',
            },
        ),
        migrations.CreateModel(
            name='WatchColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'watch color',
                'verbose_name_plural': 'watch colors',
            },
        ),
        migrations.CreateModel(
            name='WatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='watch')),
                ('price', models.FloatField()),
                ('real_price', models.FloatField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('post_views', models.IntegerField(blank=True, default=0, null=True)),
                ('long_description', ckeditor.fields.RichTextField()),
                ('additional', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='watches.watchbrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='watches.watchcategory')),
                ('color', models.ManyToManyField(related_name='watches', to='watches.WatchColor')),
            ],
            options={
                'verbose_name': 'watch',
                'verbose_name_plural': 'watches',
            },
        ),
    ]
