# Generated by Django 3.2.5 on 2021-07-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_rename_title_watchcolor_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchmodel',
            name='additional',
        ),
    ]
