# Generated by Django 3.2.5 on 2021-09-05 04:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_watchimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchbrand',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='watchbrand',
            name='title',
            field=models.CharField(max_length=25, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='watchcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='watchcategory',
            name='title',
            field=models.CharField(max_length=25, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='watchcolor',
            name='code',
            field=models.CharField(max_length=25, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='watchcolor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='watchimagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watches', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='watchimagemodel',
            name='watch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='watches.watchmodel', verbose_name='watch'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='watches.watchbrand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watches', to='watches.watchcategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='color',
            field=models.ManyToManyField(related_name='watches', to='watches.WatchColor', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='image',
            field=models.ImageField(upload_to='watch', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='long_description',
            field=ckeditor.fields.RichTextField(verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='post views'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real price'),
        ),
        migrations.AlterField(
            model_name='watchmodel',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
    ]
